### PR TITLE
added configuration for proguard-rules.pro along with some changes to…

### PR DESCRIPTION
**Pull request by suhaibroomy**
… make in work

### CODE REVIEW

**Review by abhishek11008 — APPROVED** [review]
Looks fine, no issues but we need more work in Proguard for security purpose.

**Comment by suhaibroomy** [comment]
> Looks fine, no issues but we need more work in Proguard for security purpose.

Any suggestions @abhishek11008

**Comment by abhishek11008** [comment]
We should keep all the necessary classes/libraries only that we need to use and rest we should just obfuscate whole app code normally so that reverse engineering over the app should not be possible, which is right now doable with Meraki App.

**Comment by suhaibroomy** [comment]
@abhishek11008 these changes do exactly that. This will enable code obfuscation which wasn't enabled previously.

**Pull request merged**
